openapi: 3.0.0
info:
  title: Academic Project Income Distribution API
  version: 1.0.0
  description: API for managing academic project incomes, payments, and distributions

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      required:
        - id
        - email
        - fullName
        - role
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        fullName:
          type: string
        role:
          type: string
          enum: [admin, finance_officer, academician]
        phone:
          type: string
        iban:
          type: string

    Project:
      type: object
      required:
        - id
        - code
        - name
        - budget
        - status
      properties:
        id:
          type: string
          format: uuid
        code:
          type: string
          pattern: '^PRJ-\d{4}-\d{3}$'
        name:
          type: string
        budget:
          type: number
          minimum: 0
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        status:
          type: string
          enum: [active, completed, cancelled]
        representatives:
          type: array
          items:
            $ref: '#/components/schemas/ProjectRepresentative'

    ProjectRepresentative:
      type: object
      required:
        - userId
        - sharePercentage
      properties:
        userId:
          type: string
          format: uuid
        userName:
          type: string
        sharePercentage:
          type: number
          minimum: 0
          maximum: 100
        isLead:
          type: boolean

    Income:
      type: object
      required:
        - id
        - projectId
        - grossAmount
        - vatAmount
        - netAmount
        - incomeDate
      properties:
        id:
          type: string
          format: uuid
        projectId:
          type: string
          format: uuid
        grossAmount:
          type: number
          minimum: 0
        vatRate:
          type: number
          default: 18
        vatAmount:
          type: number
        netAmount:
          type: number
        description:
          type: string
        incomeDate:
          type: string
          format: date

    Balance:
      type: object
      required:
        - userId
        - availableAmount
        - debtAmount
        - reservedAmount
      properties:
        userId:
          type: string
          format: uuid
        availableAmount:
          type: number
        debtAmount:
          type: number
        reservedAmount:
          type: number
        lastUpdated:
          type: string
          format: date-time

    PaymentInstruction:
      type: object
      required:
        - id
        - instructionNumber
        - userId
        - totalAmount
        - status
      properties:
        id:
          type: string
          format: uuid
        instructionNumber:
          type: string
          pattern: '^PAY-\d{4}-\d{3}$'
        userId:
          type: string
          format: uuid
        totalAmount:
          type: number
          minimum: 0
        status:
          type: string
          enum: [pending, approved, processing, completed, rejected]
        notes:
          type: string

    Report:
      type: object
      required:
        - type
        - parameters
      properties:
        type:
          type: string
          enum: [project, academician, company, payments]
        parameters:
          type: object
          properties:
            startDate:
              type: string
              format: date
            endDate:
              type: string
              format: date
            projectId:
              type: string
              format: uuid
            userId:
              type: string
              format: uuid
        format:
          type: string
          enum: [excel, pdf]

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: object

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      tags: [Authentication]
      summary: Register new user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - fullName
                - role
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                fullName:
                  type: string
                role:
                  type: string
                  enum: [academician]
      responses:
        201:
          description: User created
        400:
          description: Invalid input
        409:
          description: Email already exists

  /auth/login:
    post:
      tags: [Authentication]
      summary: Login user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        401:
          description: Invalid credentials

  /projects:
    get:
      tags: [Projects]
      summary: List projects
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, completed, cancelled]
      responses:
        200:
          description: Projects list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

    post:
      tags: [Projects]
      summary: Create project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - budget
                - startDate
                - representatives
              properties:
                name:
                  type: string
                budget:
                  type: number
                  minimum: 0
                startDate:
                  type: string
                  format: date
                endDate:
                  type: string
                  format: date
                representatives:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required:
                      - userId
                      - sharePercentage
                    properties:
                      userId:
                        type: string
                        format: uuid
                      sharePercentage:
                        type: number
                        minimum: 0
                        maximum: 100
                      isLead:
                        type: boolean
      responses:
        201:
          description: Project created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        400:
          description: Invalid input (e.g., shares don't sum to 100%)
        403:
          description: Insufficient permissions

  /projects/{projectId}:
    get:
      tags: [Projects]
      summary: Get project details
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Project details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: Project not found

    put:
      tags: [Projects]
      summary: Update project
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        200:
          description: Project updated
        400:
          description: Invalid input
        404:
          description: Project not found

  /income:
    post:
      tags: [Income]
      summary: Record income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - projectId
                - grossAmount
                - incomeDate
              properties:
                projectId:
                  type: string
                  format: uuid
                grossAmount:
                  type: number
                  minimum: 0
                description:
                  type: string
                incomeDate:
                  type: string
                  format: date
      responses:
        201:
          description: Income recorded
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Income'
                  - type: object
                    properties:
                      commission:
                        type: number
                      distributions:
                        type: array
                        items:
                          type: object
                          properties:
                            userId:
                              type: string
                              format: uuid
                            amount:
                              type: number
        400:
          description: Invalid input
        403:
          description: Insufficient permissions

  /income/{projectId}:
    get:
      tags: [Income]
      summary: List project incomes
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        200:
          description: Income list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Income'

  /balances:
    get:
      tags: [Balances]
      summary: Get user balances
      parameters:
        - name: userId
          in: query
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Balance information
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Balance'
                  - type: array
                    items:
                      $ref: '#/components/schemas/Balance'

  /balances/transactions:
    get:
      tags: [Balances]
      summary: Get balance transaction history
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: Transaction history
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    type:
                      type: string
                      enum: [income, payment, debt, adjustment]
                    amount:
                      type: number
                    balanceBefore:
                      type: number
                    balanceAfter:
                      type: number
                    description:
                      type: string
                    createdAt:
                      type: string
                      format: date-time

  /payment-instructions:
    get:
      tags: [Payments]
      summary: List payment instructions
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, approved, processing, completed, rejected]
      responses:
        200:
          description: Payment instructions list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentInstruction'

    post:
      tags: [Payments]
      summary: Create payment instruction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - amount
              properties:
                userId:
                  type: string
                  format: uuid
                amount:
                  type: number
                  minimum: 0
                notes:
                  type: string
      responses:
        201:
          description: Payment instruction created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentInstruction'
        400:
          description: Insufficient balance
        403:
          description: Insufficient permissions

  /payment-instructions/{instructionId}/approve:
    post:
      tags: [Payments]
      summary: Approve payment instruction
      parameters:
        - name: instructionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Payment approved
        400:
          description: Invalid status transition
        403:
          description: Insufficient permissions
        404:
          description: Instruction not found

  /payment-instructions/{instructionId}/export:
    get:
      tags: [Payments]
      summary: Export payment instruction
      parameters:
        - name: instructionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: format
          in: query
          schema:
            type: string
            enum: [csv, xml]
            default: csv
      responses:
        200:
          description: Export file
          content:
            text/csv:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        404:
          description: Instruction not found

  /reports:
    post:
      tags: [Reports]
      summary: Generate report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Report'
      responses:
        200:
          description: Report generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportId:
                    type: string
                    format: uuid
                  data:
                    type: array
                    items:
                      type: object
        400:
          description: Invalid parameters
        403:
          description: Insufficient permissions

  /reports/{reportId}/export:
    get:
      tags: [Reports]
      summary: Export report
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: format
          in: query
          required: true
          schema:
            type: string
            enum: [excel, pdf]
      responses:
        200:
          description: Report file
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
        404:
          description: Report not found